In [72]:
from urllib.request import urlretrieve
import pandas as pd
import numpy as np

In [2]:
urlretrieve("https://raw.githubusercontent.com/codebasics/nlp-tutorials/refs/heads/main/9_bag_of_words/spam.csv", './dataset/emails.csv')

('./dataset/emails.csv', <http.client.HTTPMessage at 0x254305aba40>)

In [4]:
df = pd.read_csv('./dataset/emails.csv')

In [5]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.shape

(5572, 2)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [12]:
df.groupby('Category').count()

Message
Category         
ham          4825
spam          747

In [13]:
df['spam'] = df.Category.apply(lambda x: 1 if x == 'spam' else 0)

In [14]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [38]:
x = df['Message']
y = df['spam']

In [39]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [42]:
x_train.shape

(4457,)

In [43]:
x_test.shape

(1115,)

In [44]:
type(x_test)

pandas.core.series.Series

In [45]:
x_train[0:5]

2369          If you r @ home then come down within 5 min
1138                             LOL ... No just was busy
20              Is that seriously how you spell his name?
2407    One of best dialogue in cute reltnship..!! "We...
1533    Unfortunately i've just found out that we have...
Name: Message, dtype: object

In [46]:
x_train

2369          If you r @ home then come down within 5 min
1138                             LOL ... No just was busy
20              Is that seriously how you spell his name?
2407    One of best dialogue in cute reltnship..!! "We...
1533    Unfortunately i've just found out that we have...
                              ...                        
1990    The basket's gettin full so I might be by tonight
2689    Yes I know the cheesy songs from frosty the sn...
3425    Am new 2 club & dont fink we met yet Will B gr...
1583      Yep, at derek's house now, see you Sunday &lt;3
3795    Short But Cute: "Be a good person, but dont tr...
Name: Message, Length: 4457, dtype: object

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
v = CountVectorizer()
x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<4457x7783 sparse matrix of type '<class 'numpy.int64'>'
	with 59433 stored elements in Compressed Sparse Row format>

In [54]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [57]:
x_train_cv.shape

(4457, 7783)

In [61]:
v.get_feature_names_out()[1000:1100]

array(['answers', 'answr', 'antelope', 'antha', 'anthony', 'anti',
       'antibiotic', 'any', 'anybody', 'anyhow', 'anymore', 'anyone',
       'anyones', 'anyplaces', 'anythiing', 'anythin', 'anything',
       'anythingtomorrow', 'anytime', 'anyway', 'anyways', 'anywhere',
       'aom', 'apart', 'apartment', 'apeshit', 'aphex', 'apnt', 'apo',
       'apologise', 'apologize', 'apology', 'app', 'apparently', 'appeal',
       'appear', 'appendix', 'applausestore', 'applebees', 'apples',
       'application', 'apply', 'applyed', 'applying', 'appointment',
       'appointments', 'appreciate', 'appreciated', 'approaches',
       'approve', 'approx', 'apps', 'appt', 'appy', 'april', 'aproach',
       'aquarius', 'ar', 'arab', 'arabian', 'arcade', 'archive', 'ard',
       'are', 'area', 'aren', 'arent', 'arestaurant', 'aretaking',
       'areyouunique', 'argentina', 'argh', 'argue', 'argument',
       'arguments', 'aries', 'arise', 'arithmetic', 'arm', 'armand',
       'arms', 'arng', 'arngd'

In [62]:
v.get_feature_names_out().shape

(7783,)

In [63]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [65]:
v.vocabulary_

{'if': 3617,
 'you': 7747,
 'home': 3488,
 'then': 6857,
 'come': 1911,
 'down': 2440,
 'within': 7591,
 'min': 4518,
 'lol': 4222,
 'no': 4829,
 'just': 3901,
 'was': 7432,
 'busy': 1586,
 'is': 3766,
 'that': 6839,
 'seriously': 6070,
 'how': 3535,
 'spell': 6411,
 'his': 3453,
 'name': 4718,
 'one': 4977,
 'of': 4929,
 'best': 1334,
 'dialogue': 2306,
 'in': 3662,
 'cute': 2136,
 'reltnship': 5736,
 'wen': 7496,
 'die': 2317,
 'dont': 2420,
 'near': 4752,
 'my': 4697,
 'body': 1426,
 'bcoz': 1277,
 'hands': 3325,
 'may': 4435,
 'not': 4864,
 'wipe': 7575,
 'ur': 7236,
 'tears': 6767,
 'off': 4931,
 'time': 6933,
 'gud': 3274,
 'ni8': 4801,
 'unfortunately': 7189,
 've': 7299,
 'found': 2972,
 'out': 5049,
 'we': 7456,
 'have': 3368,
 'to': 6964,
 'pick': 5246,
 'sister': 6223,
 'up': 7219,
 'from': 3027,
 'the': 6843,
 'airport': 896,
 'evening': 2672,
 'so': 6319,
 'don': 2417,
 'think': 6874,
 'll': 4196,
 'be': 1283,
 'going': 3184,
 'at': 1129,
 'all': 924,
 'should': 6158,
 'tr

In [66]:
v.get_feature_names_out()[3617]

'if'

In [69]:
x_train_np = x_train_cv.toarray()

In [86]:
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [85]:
np.where(x_train_np[0] !=0)

(array([1911, 2440, 3488, 3617, 4518, 6857, 7591, 7747]),)

In [89]:
 for k in np.where(x_train_np[0] !=0):
     print(v.get_feature_names_out()[k])
     

['come' 'down' 'home' 'if' 'min' 'then' 'within' 'you']
