In [107]:
from urllib.request import urlretrieve
import pandas as pd
import numpy as np

In [2]:
urlretrieve("https://raw.githubusercontent.com/codebasics/nlp-tutorials/refs/heads/main/9_bag_of_words/spam.csv", './dataset/emails.csv')

('./dataset/emails.csv', <http.client.HTTPMessage at 0x254305aba40>)

In [108]:
df = pd.read_csv('./dataset/emails.csv')

In [109]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [110]:
df.shape

(5572, 2)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [112]:
df.groupby('Category').count()

Message
Category         
ham          4825
spam          747

In [113]:
df['spam'] = df.Category.apply(lambda x: 1 if x == 'spam' else 0)

In [114]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [115]:
x = df['Message']
y = df['spam']

In [116]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int64

In [117]:
from sklearn.model_selection import train_test_split

In [118]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [119]:
x_train.shape

(4457,)

In [120]:
y_train.shape

(4457,)

In [122]:
y_test.shape

(1115,)

In [123]:
x_test.shape

(1115,)

In [124]:
type(x_test)

pandas.core.series.Series

In [125]:
x_train[0:5]

558              I know that my friend already told that.
2861    I want to be there so i can kiss you and feel ...
4118    Sure thing big man. i have hockey elections at...
5259    Can help u swoop by picking u up from wherever...
1695    Ü eatin later but i'm eatin wif my frens now l...
Name: Message, dtype: object

In [126]:
x_train

558              I know that my friend already told that.
2861    I want to be there so i can kiss you and feel ...
4118    Sure thing big man. i have hockey elections at...
5259    Can help u swoop by picking u up from wherever...
1695    Ü eatin later but i'm eatin wif my frens now l...
                              ...                        
2487           I dont thnk its a wrong calling between us
907     all the lastest from Stereophonics, Marley, Di...
5193                It's wylie, you in tampa or sarasota?
5061                       I think i am disturbing her da
941     No we sell it all so we'll have tons if coins....
Name: Message, Length: 4457, dtype: object

In [127]:
from sklearn.feature_extraction.text import CountVectorizer

In [128]:
v = CountVectorizer()
x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<4457x7779 sparse matrix of type '<class 'numpy.int64'>'
	with 59532 stored elements in Compressed Sparse Row format>

In [129]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [130]:
x_train_cv.shape

(4457, 7779)

In [131]:
v.get_feature_names_out()[1000:1100]

array(['anyplaces', 'anythin', 'anything', 'anythingtomorrow', 'anytime',
       'anyway', 'anyways', 'anywhere', 'aom', 'apart', 'apartment',
       'apes', 'aphex', 'apo', 'apologetic', 'apologise', 'apologize',
       'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'approaching', 'appropriate',
       'approved', 'approx', 'apps', 'appt', 'appy', 'april', 'aproach',
       'apt', 'aptitude', 'aquarius', 'ar', 'arab', 'arcade', 'archive',
       'ard', 'are', 'area', 'aren', 'arent', 'arestaurant', 'aretaking',
       'argh', 'argue', 'arguing', 'argument', 'arguments', 'aries',
       'arise', 'arithmetic', 'arm', 'armand', 'armenia', 'arms', 'arng',
       'arngd', 'around', 'aroundn', 'arrange', 'arranging', 'arrested',
       'arrival', 'arrive', 'arrived', 'arrow', 'arsenal', 'art', 'arts',
    

In [132]:
v.get_feature_names_out().shape

(7779,)

In [133]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [ ]:
v.vocabulary_

In [134]:
v.get_feature_names_out()[3617]

'idps'

In [135]:
x_train_np = x_train_cv.toarray()

In [136]:
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [137]:
np.where(x_train_np[0] !=0)

(array([ 924, 3020, 3974, 4694, 6827, 6968]),)

In [138]:
 for k in np.where(x_train_np[0] !=0):
     print(v.get_feature_names_out()[k])
     

['already' 'friend' 'know' 'my' 'that' 'told']


In [139]:
x_train[:4]

558              I know that my friend already told that.
2861    I want to be there so i can kiss you and feel ...
4118    Sure thing big man. i have hockey elections at...
5259    Can help u swoop by picking u up from wherever...
Name: Message, dtype: object

In [140]:
from sklearn.naive_bayes import MultinomialNB

In [141]:
mn = MultinomialNB()
mn.fit(x_train_cv,y_train)

MultinomialNB()

In [142]:

x_test_cv = v.transform(x_test)

In [143]:
x_test_cv.shape

(1115, 7779)

In [144]:
mn.score(x_train_cv,y_train)

0.9937177473636976

In [146]:
y_pred = mn.predict(x_test_cv)

In [147]:
mn.score(x_test_cv, y_test)

0.9865470852017937

In [151]:
from sklearn.metrics import confusion_matrix, classification_report

In [150]:
confusion_matrix(y_pred,y_test)

array([[969,  11],
       [  4, 131]])

In [153]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.97      0.92      0.95       142

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



# Creating an NLP Pipe Line

In [154]:
from sklearn.pipeline import Pipeline

In [155]:
model2 = Pipeline(
    [
        ("vectorizer", CountVectorizer()),
        ("MultinomialNB", MultinomialNB())
    ]
)

In [156]:
model2.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('MultinomialNB', MultinomialNB())])

In [158]:
pred2 = model2.predict(x_test)

In [160]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       980
           1       0.92      0.97      0.95       135

    accuracy                           0.99      1115
   macro avg       0.96      0.98      0.97      1115
weighted avg       0.99      0.99      0.99      1115

